routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('login');
// });
Route::get('/', function () {
    return view('welcome');

})->name('home');
Route::post('/login', 'UserController@login')->name('userlogin');

Route::get('/logout', 'UserController@logout')->name('logout');
Route::get('/forgot_password', function () {
    return view('forgot_password');
})->name('forgot_password');
Route::get('dashboard','DashboardController@index')->name('dashboard.index')->middleware('checktoken');

Route::resource('profile', 'ProfileController')->except('index')->middleware('checktoken');

Route::get('/forgot_password', function () {
    return view('forgot_password');
})->name('forgot_password');

Route::post('/reset_password_first', 'UserController@ResetPasswordFirst')->name('reset_password_first');

Route::get('/reset_password', function () {
    return view('reset_password');
})->name('reset_password');

Route::post('/reset_password_sec', 'UserController@ResetPasswordSec')->name('reset_password_sec');





Route::get('show_profile/{page?}','ProfileController@index')->name('profile.index')->middleware('checktoken');

Route::get('view_profile/{page?}','ProfileController@viewprofile')->name('view_profile')->middleware('checktoken');

Route::get('editprofile/{id}/edit','ProfileController@editprofile')->name('editprofile')->middleware('checktoken');
Route::put('editprofile','ProfileController@updateprofile')->name('editprofile')->middleware('checktoken');

Route::put('update_password', 'ProfileController@updatepassword')->name('update_password')->middleware('checktoken');

Route::get('change_password','ProfileController@passwordedit')->name('change_password.index')->middleware('checktoken');
Route::resource('users', 'UserController')->except('index')->middleware('checktoken');

Route::get('user_list/{page?}','UserController@index')->name('user.index')->middleware('checktoken');
Route::resource('roles', 'RoleController')->except('index')->middleware('checktoken');

Route::get('role_list/{page?}','RoleController@index')->name('role.index')->middleware('checktoken');


Route::resource('permissions', 'PermissionController')->except('index')->middleware('checktoken');

Route::get('permission_list/{page?}','PermissionController@index')->name('permission.index')->middleware('checktoken');
Route::resource('news', 'NewsController')->except('index')->middleware('checktoken');

Route::get('news_list/{page?}','NewsController@index')->name('news.index')->middleware('checktoken');

Route::resource('experience', 'ExperienceController')->except('index')->middleware('checktoken');

Route::get('experience_list/{page?}','ExperienceController@index')->name('experience.index')->middleware('checktoken');

Route::resource('purchase', 'PurchaseController')->except('index')->middleware('checktoken');

Route::get('purchase_list/{page?}','PurchaseController@index')->name('purchase.index')->middleware('checktoken');
Route::get('getprice/{exp_id}','PurchaseController@getprice')->name('getprice.ajax')->middleware('checktoken');

Route::resource('myweek', 'MyweekController')->except('index')->middleware('checktoken');

Route::get('myweek_list/{page?}','MyweekController@index')->name('myweek.index')->middleware('checktoken');


Route::post('assets/storeimage/{module}/{id}', 'AssetsController@store')->name('assets.storeimage')->middleware('checktoken');

Route::resource('assets', 'AssetsController')->except('store')->middleware('checktoken');



Route::get('{slug?}/{id}/edit/assets','AssetsController@editimage')->name('assets.edit')->middleware('checktoken');

resources/views/create_myweek.blade.php
@extends('layouts.app')
@section('content')
<style>
.jFiler-input-choose-btn {
    background: black!important;
}



</style>



<div class="page-wrapper">

    <div class="page-header m-t-50">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Create My Week</h4>
                            {{-- <span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span> --}}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">

                                    <p class="">Create My Week</p>

                            </li>


                            <li class="breadcrumb-item"><a href="{{ route('myweek.index') }}">My Week List</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-body">





    <section class="section" >


        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{{ route('myweek.store') }}" method="post" id="addUser"
                            enctype="multipart/form-data">
                            @csrf

                            @if(session('success') !== null)
                            <div class="succWrap">
                                {{ session('success') }}
                            </div>
                            <!-- <div class='alert alert-success'>
                            {{ session('success') }}
                        </div> -->
                            @endif

                            @if(session('errors') !== null)

                            @foreach(session('errors') as $v)
                            @foreach($v as $e)

                            <div class="errorWrap"><strong>ERROR</strong>: {{ $e }} </div>


                            @endforeach

                            @endforeach
                            @endif


                            @if(session('error') !== null)
                            <div class="errorWrap"><strong>ERROR</strong>: {{session('error') }} </div>

                            @endif

                            @if(session('message') !== null)
                            <div class="errorWrap"><strong>ERROR</strong>: {{session('message') }} </div>

                            @endif
                            <div class="form-group row">
                                <div class="col-sm-4">
                                    <label class="col-form-label text-md-right " >Players</label>
                                    <select class="js-example-basic-single col-sm-12" name="player_id"    class="form-control selectric " required>
                                        <option value="" >Select</option>
                                        @foreach($users as $user)
                                        <option value="{{ $user['user_id'] }}" {{ (old("id") == $user['user_id'] ? "selected":"") }}>{{ $user['name'] }}</option>
                                        @endforeach
                                    </select>
                                </div>



                                <div class="col-sm-4">
                                    <label class="col-form-label text-md-right " >Status</label>
                                    <select class="js-example-basic-single col-sm-12" name="status_id"    class="form-control selectric ">
                                        <option value="" disabled>Select</option>
                                        @foreach($statuses as $statuse)
                                        <option value="{{ $statuse['id'] }}" {{ (old("id") == $statuse['id'] ? "selected":"") }}>{{ $statuse['name'] }}</option>
                                        @endforeach
                                    </select>
                                </div>


                                <div class="col-sm-4 text-center">

                                    <label class="col-form-label text-md-right ">General Photos</label>

                                    <input type="file" name="file[]" id="filer_input" multiple="multiple" class="form-control" required>                                </div>


                        </div>













                        <div class="form-group row mb-4">
                            <label class="col-form-label text-md-right "></label>
                            <div class="col-sm-12 col-md-7 offset-5">
                                <button type="submit" class="btn ">Create News</button>
                            </div>
                        </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </section>
        </div>
    </div>
@endsection

resources/views/edit_user.blade.php
@extends('layouts.app')
@section('content')



<div class="page-wrapper">

    <div class="page-header m-t-50">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <div class="d-inline">
                            <h4>Edit User</h4>
                            {{-- <span>lorem ipsum dolor sit amet, consectetur adipisicing elit</span> --}}
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="page-header-breadcrumb">
                        <ul class="breadcrumb-title">
                            <li class="breadcrumb-item">

                                    <p class="">Edit User</p>

                            </li>


                            <li class="breadcrumb-item"><a href="{{ route('user.index') }}">User List</a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="page-body">





    <section class="section" >


        <div class="section-body">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{{route('users.update',['user'=>$user['id']]) }}" method="post" id="editUser"
                                enctype="multipart/form-data">
                                @method('PUT')
                                @csrf

                                @if(session('success') !== null)
                                <div class="succWrap">
                                {{ session('success') }}
                                </div>

                                @endif

                                @if(session('error') !== null)

                                        @foreach(session('error') as $v)
                                        @foreach($v as $e)
                                        <div class="errorWrap">
                                            {{ $e }}
                                        </div>
                                        @endforeach

                                        @endforeach
                                        {{-- <div class='alert alert-red'>
                                    {{ session('error') }}
                                </div> --}}
                                @endif

                                <div class="form-group row">
                                    <div class="col-sm-4">
                                    <label class="col-form-label text-md-right ">User name</label>
                                    <input type="text" name="name" value="{{ old('name',$user['name']) }}" class="form-control" required>
                                    </div>


                                    <div class="col-sm-4">
                                    <label class="col-form-label text-md-right ">Email Address</label>
                                    <input type="email" name="email" value="{{ old('email',$user['email']) }}" class="summernote-simple form-control" required>

                                    </div>

                                    <div class="col-sm-4">
                                    <label class="col-form-label text-md-right ">Mobile Number</label>
                                    <input type="number" name="mobile" value="{{ old('mobile',$user['mobile']) }}" class="summernote-simple form-control" required>

                                    </div>

                                    <div class="col-sm-4">
                                    <label class="col-form-label text-md-right ">Password</label>
                                    <input type="password" name="password"  class="summernote-simple form-control" required>

                                    </div>

                                    <div class="col-sm-4">
                                    <label class="col-form-label text-md-right ">Password Conformation</label>
                                    <input type="password" name="password_confirmation"  class="summernote-simple form-control" required>

                                    </div>





                                    @php

                                    $userrolesarr = [];

                                    foreach($user['roles']['data'] as $userrolesdata)
                                    {

                                        $userrolesarr[] = $userrolesdata['id'];
                                    }
                                    @endphp

                                    <div class="col-sm-3">
                                    <label class="col-form-label text-md-right ">Roles</label>
                                    <select  class="js-example-basic-single col-sm-12"  name="roles[]" id="" placeholder="Role" required multiple class="form-control selectric">
                                        <option value="">Select</option>
                                        @foreach($roles as $role)

                                            <option value="{{ $role['id'] }}" {{ (collect($userrolesarr)->contains($role['id'])) ? 'selected':((collect(old('roles'))->contains($role['id'])) ? 'selected':'') }}>{{ $role['name'] }}</option>
                                        @endforeach
                                    </select>

                                    </div>



<!-- Modal large-->
<button type="button" class="btn waves-effect" data-toggle="modal" data-target="#default-Modal" style="margin-top: 30px;height:40px">+</button>




                                               <!-- Modal large-->

                            </div>















                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right "></label>
                                <div class="col-sm-12 col-md-7 offset-5">
                                    <button type="submit" class="btn btn-blue">Update</button>
                                    <a href="{{ url('user_list') }}"
                                    class=" d-inline text-center btn font1 back" ><i
                                        class="icofont icofont-arrow-left" ></i>Back&nbsp;&nbsp;</a>
                                </div>
                            </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="default-Modal1" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Add Role</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
</button>
                    </div>
                    <div class="modal-body">
                    <form action="{{ route('roles.store') }}" method="post" id="addrole"
enctype="multipart/form-data">
@csrf
                    <div class="form-group row">
<div class="col-sm-4 offset-1">
<label class="col-form-label text-md-right ">Role name</label>
<input type="text" name="name" value="{{ old('name') }}" class="form-control" required>
</div>

<div class="col-sm-4 offset-1">
<label class="col-form-label text-md-right ">Permissions</label>
<select  class="col-sm-12"  name="permissions[]" id="" placeholder="Role" required class="form-control selectric" multiple required>
    <option value="">Select</option>
    @foreach($permissions as $permission)
        <option value="{{ $permission['id'] }}" {{ (collect(old('permissions'))->contains($permission['id'])) ? 'selected':'' }}>{{ $permission['name'] }}</option>
    @endforeach
</select>
</div>


                    </div>








                    </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
        </div>
    </div>








































@endsection
{{-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<script type="text/javascript">

$(function() {


    var password = document.getElementById("password")
  , confirm_password = document.getElementById("confirm_password");

function validatePassword(){

  if(password.value != confirm_password.value) {
    confirm_password.setCustomValidity("Password And Confirm Password Must Be Match");
  } else {
    confirm_password.setCustomValidity('');
  }
}

password.onchange = validatePassword;
confirm_password.onkeyup = validatePassword;

validatePassword;

});
</script>


 --}}

resources/views/experience_list.blade.php
@extends('layouts.app')
@section('content')


<div class="pcoded-content">
    <div class="pcoded-inner-content">
        <!-- Main-body start -->
        <div class="main-body">
            <div class="page-wrapper">
                <!-- Page-header start -->
                <div class="page-header">
                    <div class="row align-items-end">
                        <div class="col-lg-8">
                            <div class="page-header-title">
                                <div class="d-inline">
                                    <h4>Experience List</h4>
                                    {{-- <span>HTML5 buttons provides the local file saving features</span> --}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="page-header-breadcrumb">
                                <ul class="breadcrumb-title">
                                    <li class="breadcrumb-item">
                                        <a href="#"> <i class="feather icon-home"></i> </a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="{{ route('experience.index') }}">Experience List</a>
                                    </li>
                                    {{-- <li class="breadcrumb-item"><a href="#!">Button</a>
                                    </li>
                                    <li class="breadcrumb-item"><a href="#!">HTML5 Data-Export</a>
                                    </li> --}}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Page-header end -->

                    <!-- Page-body start -->
                    <div class="page-body">
                        @if(session('success') !== null)
                        <div class='succWrap'>
                            {{ session('success') }}
                        </div>
                        @endif
                        @if(session('error') !== null)
                        @foreach(session('error') as $k =>$v)
                        <div class='alert alert-danger'>
                            {{ $v[0] }}
                        </div>
                        @endforeach
                        @endif
                        <div class="row">
                            <div class="col-sm-12">
                                <!-- HTML5 Export Buttons table start -->
                                <div class="card">
                                    <div class="card-header table-card-header">
                                        {{-- <h5>HTML5 Export Buttons</h5> --}}
                                    </div>
                                    <div class="card-block">
                                        <div class="row ">
                                            <div class="col-sm-4">
                                                @if(collect(session('permissions'))->contains('Create experience'))

                                                <a class="btn btn-dark" href="{{ route('experience.create') }}" role="button">Add New</a>
                                            @endif
                                            </div>
                                            <div class="col-sm-4">
                                            </div>
                                            <div class="col-sm-4">
                                                <div class="col">
                                                    <ul id="pagination" class="" style="display: -webkit-box;">
                                                        <li style="padding: 2px;"><a href="{{ route('experience.index',$page=1) }}" class="btn  @if($pagination['current_page']==1) {{ "disabled" }} @endif" style="box-shadow: 0 2px 6px #acb5f6;
                               border-radius:30px">First</a></li>
                                                        @php
                                                        if(isset($pagination['links']['previous']))
                                                        {
                                                        # code...
                                                        $endurl = explode("?page=",$pagination['links']['previous']);
                                                        $page = $endurl[1];

                                                        @endphp
                                                        <li style="padding: 2px;"><a href="{{ route('experience.index',$page) }}" class="btn " style="box-shadow: 0 2px 6px #acb5f6;
                       border-radius:30px">Previous</a></li>
                                                        @php
                                                        }
                                                        @endphp






                                                        @php
                                                        if(isset($pagination['links']['next']))
                                                        {
                                                        $endurl = explode("?page=",$pagination['links']['next']);
                                                        $page = $endurl[1];
                                                        // echo
                                                        @endphp
                                                        <li style="padding: 2px;"> <a href="{{ route('experience.index',$page) }}" class="btn " style="box-shadow: 0 2px 6px #acb5f6;
                      border-radius:30px">Next</a></li>
                                                        @php
                                                        }

                                                        @endphp

                                                        @php
                                                        if($pagination['total_pages']>1)
                                                        {
                                                        @endphp
                                                        <li style="padding: 2px;"> <a href="{{ route('experience.index',$pagination['total_pages']) }}" class="btn  float-right" style="box-shadow: 0 2px 6px #acb5f6;
                      border-radius:30px">Last</a> </li>

                                                        @php
                                                        }

                                                        @endphp

                                                    </ul>

                                                    {{-- <a href="{{ route('product_categories.create') }}" class="btn btn-primary float-right">Add New</a> --}}

                                                </div>
                                            </div>
                                        </div>

                                        <div class="dt-responsive table-responsive">
                                            <table id="basic-btn" class="table table-striped table-bordered nowrap">
                                                <thead>
                                                    <tr>
                                                        <th>Actions</th>
                                                        <th>Image</th>
                                                        <th>Title</th>
                                                        <th>Description</th>
                                                        <th>Price</th>
                                                        <th>Created At</th>

                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach($Experience as $Experienc)
                                                    @php
                                                    $id=$Experienc['id'];
                                                    @endphp


                                                    <tr>
                                                        <td style="display: -webkit-box;">
                                                            <!-- <a  data-toggle="tooltip" data-placement="top" title="View" href="{{ url('experience/'.$id.'/edit') }}" role="button" style="color: #007bff;padding: 0.5rem;"><i class="fa fa-eye"></i></a> -->
                                                            @if(collect(session('permissions'))->contains('Update experience'))

                                                            <a data-toggle="tooltip" class=" d-inline font1 edit-confirmation" data-placement="top" title="Edit" href="{{ url('experience/'.$id.'/edit') }}" role="button" style="color: #007bff;padding: 0.5rem;"><i class="icofont icofont-ui-edit"></i></a>
                                                            @endif
                                                            <form id="delete_from_{{$Experienc['id']}}" method="POST" action="{{ route('experience.destroy', $Experienc['id']) }}">
                                                                {{ csrf_field() }}
                                                                {{ method_field('DELETE') }}

                                                                <div class="form-group">


                                                                    @if(collect(session('permissions'))->contains('Delete experience'))

                                                                    <a data-toggle="tooltip" class="_delete_data" data-placement="top" title="Delete" href="javascript:void(0);" data-id="{{$Experienc['id']}}" role="button" style="color: #007bff;padding: 0.5rem;"><i class="icofont icofont-trash"></i></a>
@endif
                                                                </div>
                                                            </form>
                                                        </td>
<td>    <img style="display: block;margin-left: auto;margin-right: auto;" src="{{ isset($Experienc['Assets']['data'][0]['links']) ? $Experienc['Assets']['data'][0]['links']['full'].'?width=100&height=75' : asset('img/no-image.gif')  }}"/></td>
                                                        <td>
                                                            {{ $Experienc['title'] }}
                                                        </td>

                                                        <td>{{ $Experienc['description'] }}</td>


                                                        <td>{{ $Experienc['price'] }}</td>


                                                        <td>{{ date("Y-m-d H:i:s",$Experienc['created_at']) }}</td>



                                                    </tr>



                                                    @endforeach








                                                </tbody>

                                            </table>
                                        </div>
                                    </div>
                                    @php

                                    $first =(($pagination['current_page']-1) * $pagination['per_page']) + 1;

                                    if($pagination['current_page']==$pagination['total_pages'])
                                    {

                                    $last = ((($pagination['current_page']-1) * $pagination['per_page']) + $pagination['count']);
                                    }
                                    else
                                    {
                                    $last = ($pagination['current_page'] * $pagination['per_page']);

                                    }


                                    $total = $pagination['total'];

                                    @endphp


                                    <p style="font-size:15px;margin-top:-17px;" class="ml-4">Showing {{ $first }} to {{ $last }} of {{ $total }}</p>
                                </div>

                                <!-- HTML5 Export Buttons end -->

                                                          </div>
                        </div>
                    </div>
                    <!-- Page-body end -->
                </div>
            </div>
        </div>

    </div>
</div>

<style>
    .pagination {

        display: none;
        float: left;
        margin-left: 10px;
        /* float:right; */
    }
</style>






@endsection